name: Cleanup Workflows

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cleanup Workflows
      run: |
        # Get all workflows
        workflows=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${{ github.repository }}/actions/workflows)

        # Extract workflow IDs
        workflow_ids=$(echo "$workflows" | jq '.workflows[].id')

        for workflow_id in $workflow_ids; do
          # Get all runs for the workflow
          runs=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs)

          # Extract run IDs and statuses
          run_ids=$(echo "$runs" | jq '.workflow_runs[] | select(.status != "completed") | .id')

          for run_id in $run_ids; do
            # Cancel the run if it's still in progress
            curl -X POST \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel

            # Delete the run
            curl -X DELETE \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id
          done
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
