name: Delete All Releases and Tags

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all releases
      run: |
        response=$(curl -H "Authorization: token ${{ secrets.GET_ACTIONS }}" -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases")
        if [[ "$response" != "[]" ]]; then
          releases=$(echo "$response" | jq -r '.[].id')
          for release_id in $releases; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GET_ACTIONS }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id"
          done
        fi
      shell: /usr/bin/bash -e {0}

    - name: Delete all tags
      run: |
        tags=$(git tag)
        for tag in $tags; do
          git tag -d $tag
          git push --delete origin $tag
        done
      shell: /usr/bin/bash -e {0}
