name: Delete All Releases and Tags

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all releases
      run: |
        releases=$(curl -H "Authorization: token ${{ secrets.GET_ACTIONS }}" -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | jq -r '.[].id')
        for release_id in $releases; do
          curl -X DELETE -H "Authorization: token ${{ secrets.GET_ACTIONS }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/$release_id"
        done

    - name: Delete all tags
      run: |
        tags=$(git tag)
        for tag in $tags; do
          git tag -d $tag
          git push --delete origin $tag
        done
