name: Cleanup All Releases and Tags

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete all releases and tags
      run: |
        # Fetch all tags
        git fetch --tags

        # Delete all releases
        releases=$(curl -H "Authorization: token ${{ secrets.GIT_ACTIONS }}" -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[].id')
        for release in $releases; do
          curl -H "Authorization: token ${{ secrets.GIT_ACTIONS }}" -X DELETE https://api.github.com/repos/${{ github.repository }}/releases/$release
        done

        # Delete all tags
        tags=$(git tag)
        for tag in $tags; do
          git push --delete origin $tag
        done
      env:
        GIT_ACTIONS: ${{ secrets.GIT_ACTIONS }}
