name: Delete All Releases and Tags

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all releases
      run: |
        releases=$(gh release list | awk '{print $1}')
        for release_id in $releases; do
        gh release delete $release_id --yes
        done
      shell: /usr/bin/bash -e {0}
      env:
        GH_TOKEN: ***
